sonar.projectKey=sample-azure-func-api
sonar.organization=your-org
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.coverage.exclusions=**/Program.cs,**/Startup.cs
sonar.cpd.exclusions=**/Migrations/**
